version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install

  pre_build:
    commands:
      - npm run build

  build:
    commands:
      - echo Build phase

  post_build:
    commands:
      - echo Post-build phase

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/
