version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo DB_HOST=${RDS_HOSTNAME} >> .env
      - echo DB_PORT=${RDS_PORT} >> .env
      - echo DB_NAME=${RDS_DB_NAME} >> .env
      - echo DB_USER=${RDS_USERNAME} >> .env
      - echo DB_PASS=${RDS_PASSWORD} >> .env
      - echo JWT_SECRET=${JWT_SECRET} >> .env
      - echo JWT_EXPIRES=${JWT_EXPIRES} >> .env
      - npm install

  pre_build:
    commands:
      - npm run build

  build:
    commands:
      - echo Build phase

  post_build:
    commands:
      - echo Post-build phase

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/
