version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo DB_HOST=${DB_HOST} >> .env
      - echo DB_PORT=${DB_PORT} >> .env
      - echo DB_NAME=${DB_NAME} >> .env
      - echo DB_USER=${DB_USER} >> .env
      - echo DB_PASS=${DB_PASS} >> .env
      - echo JWT_SECRET=${JWT_SECRET} >> .env
      - echo JWT_EXPIRES=${JWT_EXPIRES} >> .env
      - npm install

  pre_build:
    commands:
      - npm run build

  build:
    commands:
      - echo Build phase

  post_build:
    commands:
      - echo Post-build phase

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/
